import { useState } from 'react'

const TABS = [
  { id: 'email', label: 'Email' },
  { id: 'cover', label: 'Cover Letter' },
  { id: 'resume', label: 'Resume Suggestions' },
]

function copyText(text) {
  if (!text) return
  navigator.clipboard?.writeText(text)
}

export default function ResultTabs({ results, loading = false }) {
  const [activeTab, setActiveTab] = useState('email')

  const content = {
    email: results?.generated_email || '',
    cover: results?.generated_cover_letter || '',
    resume: results?.resume_suggestions || '',
  }

  if (!results) {
    return (
      <div className="panel-card empty-panel">
        <div className="panel-card-header">
          <div>
            <span className="section-kicker">AI output</span>
            <h3>Generated results</h3>
          </div>
        </div>
        {loading ? (
          <div className="result-skeleton-wrap">
            <div className="result-skeleton short" />
            <div className="result-skeleton medium" />
            <div className="result-skeleton long" />
            <div className="result-skeleton medium" />
          </div>
        ) : (
          <p>Your AI-generated materials will appear here after you submit the form.</p>
        )}
      </div>
    )
  }

  return (
    <div className="panel-card results-card">
      <div className="panel-card-header">
        <div>
          <span className="section-kicker">Generated by AI</span>
          <h3>Generated results</h3>
          <p>Review, copy, and refine your latest application assets.</p>
        </div>
        <div className="pill-stack">
          <span className="soft-pill accent">Live draft</span>
          <button type="button" className="btn-ghost" onClick={() => copyText(content[activeTab])}>
            Copy
          </button>
        </div>
      </div>

      <div className="tab-row">
        {TABS.map((tab) => (
          <button
            key={tab.id}
            type="button"
            className={`tab-button ${activeTab === tab.id ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div className="result-body">
        <pre>{content[activeTab]}</pre>
      </div>
    </div>
  )
}